version: 2.1

orbs:
  # use latest version (volatile) for artsy managed orbs
  hokusai: artsy/hokusai@volatile
  horizon: artsy/release@volatile

jobs:

  detect-secrets:
    docker:
      - image: artsy/detect-secrets:ci # pragma: allowlist secret
    resource_class: small
    working_directory: /usr/src/app
    steps:
      - checkout
      - run: git ls-files -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline --verbose

not_main_or_staging_or_release: &not_main_or_staging_or_release
  filters:
    branches:
      ignore:
        - main
        - staging
        - release

not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release

only_main: &only_main
  context: hokusai
  filters:
    branches:
      only: main

only_release: &only_release
  context: hokusai
  filters:
    branches:
      only: release

workflows:
  build-deploy:
    jobs:
      - detect-secrets:
          <<: *not_main_or_staging_or_release

      - horizon/block:
          <<: *only_release
          context: horizon
          project_id: 271

      - hokusai/test:
          <<: *not_staging_or_release

      - hokusai/push:
          name: push-staging-image
          <<: *only_main
          requires:
            - hokusai/test

      - hokusai/deploy-staging:
          <<: *only_main
          project-name: opstools
          requires:
            - push-staging-image

      - hokusai/deploy-production:
          <<: *only_release
          requires:
            - horizon/block
