---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: opstools-terraform-drift-detection
spec:
  schedule: "15 7 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        spec:
          containers:
            - name: opstools-terraform-drift-detection
              image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/opstools:staging
              command: ["terraform_drift_detection/detect.py"]
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: opstools-environment
          restartPolicy: Never
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                    - background
